config/routes.rb
Worldcup2014::Application.routes.draw do
  get "pages/rules"
  get 'results', to: 'results#index'
  get 'excel', to: 'results#excel'
  
  resources :forecasts

  resources :users do
    resources :scores
    get 'scores_excel', to: 'scores#excel'
  end

  root 'forecasts#index'

  

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user
	belongs_to :forecast

	attr_accessible :user_id, :forecast_id, :points, :reason, :type_of_bet

	def self.calculate_results_per_day(date)

		games = Game.get_games_per_day(date)

		games.each do |game|
			
			Rails.logger.info("#{game["team1"]} vs #{game["team2"]}: #{game["score1"]} - #{game["score2"]}")

			@group = Setup.groups.select{|k,v| v.include?(game["team1"])}.each_key.peek

			@forecasts = game.round <= 15 ? Forecast.all.where(group: "#{@group}", game_id: nil) : game.round

			@forecasts.each do |f|
	  		if game.round <= 15
		  		forecast_winner = find_winner(f.forecast1.to_i,f.forecast2.to_i)
		  		result_winner = game.result.to_s

					@points = game["score1"]==f.forecast1 && game["score2"]==f.forecast2 ? 5 : (forecast_winner==result_winner ? 2 : 0)
					@reason = "Partido: #{Setup.teams[game["team1"]]} vs #{Setup.teams[game["team2"]]}. Resultado: #{game["score1"]} - #{game["score2"]}"
				elsif game.round == 19
					@points = Setup.finalists[2]==f.forecast1.to_s ? 10 : 0
					@points += Setup.finalists[3]==f.forecast2.to_s ? 8 : 0
					@reason = "Partido: #{Setup.teams[game["team1"]]} vs #{Setup.teams[game["team2"]]}. Tercero: #{Setup.finalists[2]}. Cuarto: #{Setup.finalists[3]}"
				else
					@points = Setup.finalists[0]==f.forecast1.to_s ? 15 : 0
					@points += Setup.finalists[1]==f.forecast2.to_s ? 12 : 0
					@reason = "Partido: #{Setup.teams[game["team1"]]} vs #{Setup.teams[game["team2"]]}. Campeón: #{Setup.finalists[0]}. SubCampeón: #{Setup.finalists[1]}"
				end

				Rails.logger.info("#{f.user.name}: #{f.forecast1} - #{f.forecast2}. Points: #{@points}")

				Score.create(:user_id => f.user_id, :forecast_id => f.id, :points => @points, 
					:reason => @reason, :type_of_bet => 1)

				if(game.round == 20 && 	(self.sum_last_two_matches(f.user))==0)
					last_two_forecasts = Forecast.where(group: [19,20], user_id: f.user_id)

					@points = Setup.finalists.include?(last_two_forecasts.first.forecast1) ? 5 : 0
					@points += Setup.finalists.include?(last_two_forecasts.first.forecast2) ? 5 : 0
					@points += Setup.finalists.include?(last_two_forecasts.last.forecast1) ? 5 : 0
					@points += Setup.finalists.include?(last_two_forecasts.last.forecast2) ? 5 : 0

					@reason = "Total puntos obtenidos por Campeón - SubCampeón - 3ro y 4to"

					Score.create(:user_id => f.user_id, :forecast_id => f.id, :points => @points, 
					:reason => @reason)
				end
			end
			game.update(processed: true)
			User.prepare_mail(true)
		end
	end

	def self.calculate_finalists
		@finalists = Setup.finalists
		@forecasts = Forecast.where(group: ["19","20"])

		@forecasts.each do |f|
			@points = 0
			if((@finalists.include?(f.forecast1))||(@finalists.include?(f.forecast2)))
				index = @finalists.index(f.forecast1)
				index2 = @finalists.index(f.forecast2)

				if(index==2 && f.group == "19")
					@points += 10
					@reason = "Puntos por acertar 3er lugar."
				elsif(index2==3 && f.group == "19")
					@points += 8
					@reason = "Puntos por acertar 4to lugar."
				elsif(index==0 && f.group == "20")
					@points += 15
					@reason = "Puntos por acertar campeón."
				elsif(index2==1 && f.group == "20")
					@points += 12
					@reason = "Puntos por acertar SubCampeón"
				else
					@points += 5 unless index.nil?
					@points += 5 unless index2.nil?
					@reason = "Total puntos porque #{Setup.teams[f.forecast1]} o #{Setup.teams[f.forecast2]} están en los primeros 4 lugares."
				end
			end
			Rails.logger.info("Usuario: #{f.user.name}. Index: #{index} - Index2: #{index2}. Points: #{@points}")

			if(@points==0)
				@reason = "No obtuviste puntos con #{Setup.teams[f.forecast1]} o #{Setup.teams[f.forecast2]} en los primeros 4 lugares."
			end

			Score.create(:user_id => f.user_id, :forecast_id => f.id, :points => @points, :reason => @reason, :type_of_bet => 1)
		end
	end

	def self.calculate_results_per_day_excel(date)
		games = Game.get_games_per_day_excel(date)
		games.each do |game|
			Rails.logger.info("#{game["team1"]} vs #{game["team2"]}: #{game["score1"]} - #{game["score2"]}")
			p "#{game["team1"]} vs #{game["team2"]}: #{game["score1"]} - #{game["score2"]}"

			@forecasts = Forecast.all.where(game_id: "#{game.id}")

			@forecasts.each do |f|
				forecast_winner = find_winner(f.forecast1.to_i,f.forecast2.to_i)
		  	result_winner = game.result.to_s

		  	@points = game["score1"]==f.forecast1 && game["score2"]==f.forecast2 ? 5 : (forecast_winner==result_winner ? 2 : 0)

				@reason = "Partido: #{Setup.teams[game["team1"]]} vs #{Setup.teams[game["team2"]]}. Resultado: #{game["score1"]} - #{game["score2"]}"
		  	
		  	Score.create(:user_id => f.user_id, :forecast_id => f.id, :points => @points, 
					:reason => @reason, :type_of_bet => 2)
			end
			game.update(processed_excel: true)
			User.prepare_mail(false)
		end
	end

	def self.find_winner(score1,score2)
		(score1==score2) ? 'D' : ((score1>score2) ? 'L' : 'V')
	end

	def self.grab_sum_per_user(user_id,type_of_bet)
		Score.where(user_id: user_id).where(:type_of_bet => type_of_bet).sum(:points)
	end

	def self.sum_last_two_matches(user)
		Score.where(created_at: (Time.now.midnight - 1.day)..Time.now, user_id: user).sum(:points)
	end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = User.find(params[:user_id]).scores.where(:type_of_bet => 1)
    render "scores/index", locals: {type_of_bet: "1", name: @scores.first.user.name}
  end

  def excel
    @scores = User.find(params[:user_id]).scores.where(:type_of_bet => 2)
    render "scores/index", locals: {type_of_bet: "2", name: @scores.first.user.name}
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:points, :reason, :user_id, :forecast_id)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :forecast_id %><br>
    <%= f.number_field :forecast_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<div class='col-lg-6'>
  <h1>Resultados de <%=name%></h1> 
</div>
<div class='col-lg-6'>
  <h3><%= link_to "Volver", type_of_bet=="1" ? results_path : excel_path %></h3> 
</div>

<div class="well">
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Puntos</th>
        <th>Comentario</th>
        <th>Predicción</th>
      </tr>
    </thead>

    <tbody>
      <% @scores.each do |score| %>
        <tr >
          <td><span class="<%= 'badge' if score.points.to_i > 0%>"><%= score.points %></span></td>
          <td><%= score.reason %></td>
          <td><%= "#{score.forecast.forecast1} - #{score.forecast.forecast2}"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>   
  <h2> <p>Total Puntos: <strong><%= @scores.blank? ? 0 : Score.grab_sum_per_user(@scores.first.user_id,type_of_bet)%></strong></p></h2>   
</div>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Points:</strong>
  <%= @score.points %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @score.reason %>
</p>

<p>
  <strong>User:</strong>
  <%= @score.user_id %>
</p>

<p>
  <strong>Forecast:</strong>
  <%= @score.forecast_id %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>