config/routes.rb
Worldcup2014::Application.routes.draw do
  get "pages/rules"
  get 'results', to: 'results#index'
  get 'excel', to: 'results#excel'
  
  resources :forecasts

  resources :users do
    resources :scores
    get 'scores_excel', to: 'scores#excel'
  end

  root 'forecasts#index'

  

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
  	@results = User.all.sort_by(&:score_sum).reverse.reject{|u| u.forecasts.where(game_id:nil).size==0}
  end

  def excel
	@results = User.all.sort_by(&:score_sum2).reverse.reject{|u| u.forecasts.where.not(game_id:nil).size==0}
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/excel.html.erb
<h1>Y quién va ganando en la polla de Excel?</h1>

<div class="well">
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Num</th>
        <th>Jugador</th>
        <th>Puntos</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each_with_index do |user,i| %>
        <tr class=<%= "success" if i==0%>>
          <td><%= i+1 %></td>
          <td><%= link_to "#{user.name}", user_scores_excel_path(user)  %></td>
          <td><%= user.score_sum2 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/results/index.html.erb
<h1>Y quién va ganando?</h1>

<div class="well">
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Num</th>
        <th>Player</th>
        <th>Points</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each_with_index do |user,i| %>
        <tr class=<%= "success" if i==0%>>
          <td><%= i+1 %></td>
          <td><%= link_to "#{user.name}", user_scores_path(user)  %></td>
          <td><%= user.score_sum %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>