config/routes.rb
Worldcup2014::Application.routes.draw do
  get "pages/rules"
  get 'results', to: 'results#index'
  get 'excel', to: 'results#excel'
  
  resources :forecasts

  resources :users do
    resources :scores
    get 'scores_excel', to: 'scores#excel'
  end

  root 'forecasts#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polla TLM 2014</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Brasil 2014</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if current_page?('/forecasts')%>">
      	<%= link_to "Predicciones Polla Suerte", forecasts_path  %>
      </li>
      <li class="<%= 'active' if current_page?('/results')%>">
      	<%= link_to "Resultados Polla Suerte", results_path  %>
      </li>
      <li class="<%= 'active' if current_page?('/users')%>">
      	<%= link_to "Usuarios", users_path  %>
      </li>
      <li class="<%= 'active' if current_page?('/pages/rules')%>">
        <%= link_to "Reglas", pages_rules_path  %>
      </li>
    </ul>
  </div>
</div>

<%= yield %>

  <div class="panel-footer">
    <div class='row'>
      <div class='col-lg-3'>
        <%= link_to "Predicciones Polla Suerte", forecasts_path  %>
      </div>
      <div class='col-lg-3'>
        <%= link_to "Resultados Polla Suerte", results_path  %>
      </div>
      <div class='col-lg-3'>
        <%= link_to "Usuarios", users_path  %>
      </div>
      <div class='col-lg-3'>
        <%= link_to "Reglas", pages_rules_path  %>
      </div>
    </div>
  </div>

</body>
</html>